export type VehicleImage = { url: string | null; alt: string }

export type Vehicle = {
  id: number
  slug: string
  brand: string
  model: string
  title: string
  variant: string
  year: number
  firstReg: string
  price: number
  priceDisplay: string
  km: number
  status: 'dostupno' | 'prodano'
  fuel: string
  transmission: string
  power: string
  displacement: string
  color: string
  bodyType: string
  doors: number
  seats: number
  drive: string
  vatIncluded: boolean
  warranty?: string
  description: string
  equipment: string[]
  images: VehicleImage[]
}

export const ALL_VEHICLES: Vehicle[] = [
  {
    id: 1,
    slug: 'bmw-420d-xdrive-gran-coupe',
    brand: 'BMW',
    model: '420d xDrive Gran Coupé',
    title: 'BMW 420d xDrive Gran Coupé',
    variant: 'LCI M Sport · Brooklyn Grau',
    year: 2023,
    firstReg: '09/2023',
    price: 48900,
    priceDisplay: '48.900 €',
    km: 62000,
    status: 'dostupno',
    fuel: 'Diesel',
    transmission: 'Automatik (8-stupanjski)',
    power: '140 kW / 190 KS',
    displacement: '1.995 ccm',
    color: 'Brooklyn Grau Metallic',
    bodyType: 'Gran Coupé',
    doors: 4,
    seats: 5,
    drive: 'AWD (xDrive)',
    vatIncluded: true,
    warranty: 'Do 09/2026',
    description:
      'BMW 420d xDrive Gran Coupé u odličnom stanju, servisna povijest dostupna. Vozilo dolazi s M Sport paketom koji uključuje sportski ovjes, M sport upravljač i shadow line paket. Pogon na sve kotače xDrive, automatik s 8 stupnjeva i paddle shiftersi. Sva dokumentacija uredna, jamstvo tvornice vrijedi do 09/2026.',
    equipment: [
      'M Sport paket (ovjes, upravljač, shadow line)',
      'Sustav asistencije pri vožnji s autonomnim funkcijama',
      'Adaptivni LED far s laserskim dodatakom',
      'Head-Up Display',
      'Automatska klima 3-zonska',
      'Grijana prednja sjedala',
      'Harman/Kardon glazbeni sustav',
      'Ambijentalna unutarnja rasvjeta',
      'Punjač za mobitel bežično',
      'Parking asistent + kamera 360°',
      'eSIM konekcija',
      'Električna sklopiva zrcala s memorijom',
      '20" Individual felge 826I',
      'Zatamnjena stražnja stakla',
      'Aktivna zaštita pješaka',
      'Automatski daleki svjetla',
      'Lumbar podrška sjedala',
      'Sport sedišta (kombinirani mat/koža)',
    ],
    images: [
      { url: '/car3.jpg', alt: 'BMW 420d GC xDrive LCI' },
      { url: null, alt: 'Prednji desno' },
      { url: null, alt: 'Bočni lijevo' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
      { url: null, alt: 'Instrumentna ploča' },
      { url: null, alt: 'Prtljažnik' },
      { url: null, alt: 'Motor' },
    ],
  },
  {
    id: 2,
    slug: 'porsche-macan-s-pdk',
    brand: 'Porsche',
    model: 'Macan S',
    title: 'Porsche Macan S',
    variant: '3.0 V6 PDK · Spyder 20" felge',
    year: 2019,
    firstReg: '04/2019',
    price: 56800,
    priceDisplay: '56.800 €',
    km: 72000,
    status: 'dostupno',
    fuel: 'Benzin',
    transmission: 'PDK (7-stupanjski)',
    power: '260 kW / 354 KS',
    displacement: '2.995 ccm',
    color: 'Mahogany Metallic',
    bodyType: 'SUV',
    doors: 5,
    seats: 5,
    drive: 'AWD (Porsche Traction Management)',
    vatIncluded: true,
    warranty: undefined,
    description:
      'Porsche Macan S s 3.0 V6 biturbo motorom i PDK mjenjačem — vozilo koje kombinira sportske performanse s praktičnošću SUV-a. 20" Spyder felge, sport chrono paket i panoramski krov čine ovo vozilo izuzetnom ponudom na tržištu. Servisna povijest dokumentirana kod ovlaštenog servisa.',
    equipment: [
      'Sport Chrono paket',
      '20" Spyder felge',
      'Panoramski krov',
      'BOSE glazbeni sustav',
      'PCM navigacija',
      'Grijana i ventilirana prednja sjedala',
      'Kožna unutrašnjost',
      'Adaptivni sport ovjes (PASM)',
      'Porsche Active Suspension Management',
      'Lane Departure Warning',
      'ParkAssist prednji i stražnji',
      'Kamera za vožnju unatrag',
      'LED DRL farovi',
      'Sportski ispušni sustav',
      'Automatska klima 3-zonska',
      'Električni otvarač prtljažnika',
      'Grijani prednji dio vjetrobrana',
    ],
    images: [
      { url: '/car2.jpg', alt: 'Porsche Macan S V6 PDK' },
      { url: null, alt: 'Prednji desno' },
      { url: null, alt: 'Bočni desno' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
      { url: null, alt: 'Instrumentna ploča' },
      { url: null, alt: 'Prtljažnik' },
      { url: null, alt: 'Motor' },
    ],
  },
  {
    id: 3,
    slug: 'mini-countryman-jcw-all4',
    brand: 'MINI',
    model: 'Countryman JCW ALL4',
    title: 'MINI Countryman JCW',
    variant: 'ALL4 · H&K · 300 KS · XL Paket',
    year: 2025,
    firstReg: '01/2025',
    price: 49800,
    priceDisplay: '49.800 €',
    km: 19500,
    status: 'prodano',
    fuel: 'Benzin',
    transmission: 'Automatik (8-stupanjski)',
    power: '221 kW / 300 KS',
    displacement: '1.998 ccm',
    color: 'Chili Red',
    bodyType: 'SUV',
    doors: 5,
    seats: 5,
    drive: 'AWD (ALL4)',
    vatIncluded: false,
    warranty: 'Do 01/2027',
    description:
      'MINI Countryman JCW ALL4 u savršenom stanju s Harman/Kardon glazbenim sustavom i XL paketom. Najsnažniji Countryman s 300 KS, pogon na sve kotače i sportskim JCW ovjesom. Vozilo s niskim kilometražom i tvorničkim jamstvom.',
    equipment: [
      'JCW sport ovjes',
      'Harman/Kardon glazbeni sustav',
      'XL panoramski krov',
      'Ambijentalna rasvjeta',
      'Heads-Up Display',
      'Kamera 360°',
      'Adaptivni tempomat',
      'Grijana sjedala',
      'Wireless Apple CarPlay / Android Auto',
      'JCW sport kočioni sustav',
      'John Cooper Works sportski ispuh',
    ],
    images: [
      { url: '/car1.jpg', alt: 'Mini Countryman JCW All4' },
      { url: null, alt: 'Prednji desno' },
      { url: null, alt: 'Bočni lijevo' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
      { url: null, alt: 'Instrumentna ploča' },
    ],
  },
  {
    id: 4,
    slug: 'audi-s3-quattro-limo-2024',
    brand: 'Audi',
    model: 'S3 Quattro Limuzina',
    title: 'Audi S3 Quattro Limo',
    variant: 'MY2025 · Matrix · 333 KS · MMI Plus',
    year: 2024,
    firstReg: '03/2024',
    price: 51000,
    priceDisplay: '51.000 €',
    km: 19500,
    status: 'prodano',
    fuel: 'Benzin',
    transmission: 'S tronic (7-stupanjski)',
    power: '245 kW / 333 KS',
    displacement: '1.984 ccm',
    color: 'Navarra Plava Metallic',
    bodyType: 'Limuzina',
    doors: 4,
    seats: 5,
    drive: 'AWD (Quattro)',
    vatIncluded: false,
    warranty: 'Do 03/2026',
    description:
      'Audi S3 Quattro Limuzina modelne godine 2025 s Matrix LED farovima i MMI Plus navigacijom. 333 KS, Quattro pogon i S tronic mjenjač u kombinaciji s Navarra plavom bojom.',
    equipment: [
      'Matrix LED farovi',
      'MMI Plus navigacija s 10.1" zaslonom',
      'Audi virtual cockpit Plus',
      'S sport sjedala s integriranim naslonom za glavu',
      'Automatska klima 3-zonska',
      'Adaptivni tempomat',
      'Lane Assist',
      'Bang & Olufsen glazbeni sustav',
      'S ovjes (30 mm niži)',
      'Kamera za vožnju unatrag',
    ],
    images: [
      { url: '/car4.jpg', alt: 'Audi S3 333ks 2025 Matrix' },
      { url: null, alt: 'Bočni lijevo' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
      { url: null, alt: 'Instrumentna ploča' },
    ],
  },
  {
    id: 5,
    slug: 'mercedes-glb-200d-amg',
    brand: 'Mercedes',
    model: 'GLB 200d',
    title: 'Mercedes GLB 200d',
    variant: 'AMG Paket · LED · WideScreen',
    year: 2021,
    firstReg: '06/2021',
    price: 39000,
    priceDisplay: '39.000 €',
    km: 54000,
    status: 'prodano',
    fuel: 'Diesel',
    transmission: 'DCT (8-stupanjski)',
    power: '110 kW / 150 KS',
    displacement: '1.950 ccm',
    color: 'Polar White',
    bodyType: 'SUV',
    doors: 5,
    seats: 5,
    drive: 'FWD',
    vatIncluded: false,
    warranty: undefined,
    description: 'Mercedes-Benz GLB 200d s AMG Line paketom, multibeam LED farovima i MBUX WideScreen sustavom.',
    equipment: [
      'AMG Line eksterijerni paket',
      'AMG Line interijer',
      'MBUX WideScreen (2x 10.25")',
      'Multibeam LED farovi',
      'Automatska klima 2-zonska',
      'Grijana prednja sjedala',
      'Kamera za vožnju unatrag',
      '18" AMG felge',
    ],
    images: [
      { url: '/car5.jpg', alt: 'Mercedes Benz GLB 200d AMG' },
      { url: null, alt: 'Bočni lijevo' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
    ],
  },
  {
    id: 6,
    slug: 'audi-ur-quattro-klasik',
    brand: 'Audi',
    model: 'UR Quattro',
    title: 'Audi UR Quattro',
    variant: 'Original RHD · Klasik',
    year: 1985,
    firstReg: '01/1985',
    price: 55000,
    priceDisplay: '55.000 €',
    km: 207000,
    status: 'prodano',
    fuel: 'Benzin',
    transmission: 'Manualik (5-stupanjski)',
    power: '147 kW / 200 KS',
    displacement: '2.133 ccm',
    color: 'Alpine White',
    bodyType: 'Coupé',
    doors: 3,
    seats: 4,
    drive: 'AWD (Quattro)',
    vatIncluded: false,
    warranty: undefined,
    description: 'Legendarni Audi UR Quattro iz 1985. godine, originalni RHD (desna volan), iznimno očuvan primjerak. Klasično vozilo koje osvaja na svakom izlasku.',
    equipment: ['Originalni RHD (desni volan)', 'Turbo 5-cilindar', 'Quattro stalni pogon', 'Sport sjedala', 'Originalni interijer'],
    images: [
      { url: null, alt: 'Prednji lijevo' },
      { url: null, alt: 'Bočni lijevo' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
    ],
  },
  {
    id: 7,
    slug: 'skoda-kamiq-fl-dsg',
    brand: 'Škoda',
    model: 'Kamiq FL Selection DSG',
    title: 'Škoda Kamiq FL DSG',
    variant: 'FL Selection DSG · 1.0 TSI',
    year: 2024,
    firstReg: '02/2024',
    price: 20850,
    priceDisplay: '20.850 €',
    km: 42500,
    status: 'prodano',
    fuel: 'Benzin',
    transmission: 'DSG (7-stupanjski)',
    power: '85 kW / 115 KS',
    displacement: '999 ccm',
    color: 'Magic Black Metallic',
    bodyType: 'SUV',
    doors: 5,
    seats: 5,
    drive: 'FWD',
    vatIncluded: false,
    warranty: 'Do 02/2026',
    description: 'Škoda Kamiq facelift u Selection opremi s DSG mjenjačem. Odlično opremljenost za razumnu cijenu — navigacija, kamera, LED farovi.',
    equipment: ['LED farovi', 'Navigacija', 'Kamera za vožnju unatrag', 'Automatska klima 2-zonska', 'Grijana prednja sjedala', 'Apple CarPlay / Android Auto', '17" aluminijske felge'],
    images: [
      { url: null, alt: 'Prednji lijevo' },
      { url: null, alt: 'Bočni lijevo' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
    ],
  },
  {
    id: 8,
    slug: 'mini-countryman-sd-f60',
    brand: 'MINI',
    model: 'Countryman SD Automatik',
    title: 'Mini Countryman SD',
    variant: 'F60 Automatik · Panorama · HUD · Koža',
    year: 2017,
    firstReg: '09/2017',
    price: 18500,
    priceDisplay: '18.500 €',
    km: 139000,
    status: 'prodano',
    fuel: 'Diesel',
    transmission: 'Automatik (8-stupanjski)',
    power: '140 kW / 190 KS',
    displacement: '1.995 ccm',
    color: 'Midnight Black Metallic',
    bodyType: 'SUV',
    doors: 5,
    seats: 5,
    drive: 'AWD (ALL4)',
    vatIncluded: false,
    warranty: undefined,
    description: 'MINI Countryman SD F60 s panoramskim krovom, Head-Up Displayom i kožnom unutrašnjosti. Automatik i ALL4 pogon — idealan za svakodnevnu vožnju i putovanja.',
    equipment: ['Panoramski krov', 'Head-Up Display', 'Kožna unutrašnjost', 'Grijana sjedala', 'Navigacija', 'Harman/Kardon', 'Kamera za vožnju unatrag', 'LED farovi', 'ALL4 pogon'],
    images: [
      { url: null, alt: 'Prednji lijevo' },
      { url: null, alt: 'Bočni lijevo' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
    ],
  },
  {
    id: 9,
    slug: 'bmw-m235i-n55',
    brand: 'BMW',
    model: 'M235i',
    title: 'BMW M235i',
    variant: 'N55 · H&K · Adaptivni LED · Koža',
    year: 2015,
    firstReg: '05/2015',
    price: 25200,
    priceDisplay: '25.200 €',
    km: 172000,
    status: 'prodano',
    fuel: 'Benzin',
    transmission: 'Manualik (6-stupanjski)',
    power: '240 kW / 326 KS',
    displacement: '2.979 ccm',
    color: 'Mineral Grey Metallic',
    bodyType: 'Coupé',
    doors: 2,
    seats: 4,
    drive: 'RWD',
    vatIncluded: false,
    warranty: undefined,
    description: 'BMW M235i s legendarnim N55 inline-6 motorom, ručnim mjenjačem i M Performance dodacima. Harman/Kardon audio i adaptivni LED farovi.',
    equipment: ['Harman/Kardon audio', 'Adaptivni LED farovi', 'Kožna sport sjedala', 'M Sport upravljač', 'Adaptivni ovjes', 'Head-Up Display', '19" felge', 'iDrive 6.0 navigacija'],
    images: [
      { url: null, alt: 'Prednji lijevo' },
      { url: null, alt: 'Bočni lijevo' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
    ],
  },
  {
    id: 10,
    slug: 'bmw-x3-30d-xdrive',
    brand: 'BMW',
    model: 'X3 xDrive30d',
    title: 'BMW X3 30d',
    variant: 'xDrive · Adaptivni LED · 360° · Individual',
    year: 2020,
    firstReg: '11/2020',
    price: 49950,
    priceDisplay: '49.950 €',
    km: 50000,
    status: 'prodano',
    fuel: 'Diesel',
    transmission: 'Automatik (8-stupanjski)',
    power: '210 kW / 286 KS',
    displacement: '2.993 ccm',
    color: 'Phytonic Blue Metallic',
    bodyType: 'SUV',
    doors: 5,
    seats: 5,
    drive: 'AWD (xDrive)',
    vatIncluded: false,
    warranty: undefined,
    description: 'BMW X3 xDrive30d u Individual izvedbi s laserskim farovima, kamerom 360° i panoramskim krovom. Jedno od najopremljeniijh X3 na tržištu.',
    equipment: ['Laserski farovi (adaptivni LED)', 'Kamera 360°', 'Panoramski krov', 'Individual leatherette', 'Harman/Kardon audio', 'Head-Up Display', 'Parking asistent', 'Adaptivni tempomat', '20" Individual felge', 'Ambijentalna rasvjeta'],
    images: [
      { url: null, alt: 'Prednji lijevo' },
      { url: null, alt: 'Bočni lijevo' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
    ],
  },
  {
    id: 11,
    slug: 'mini-cooper-s-f56',
    brand: 'MINI',
    model: 'Cooper S',
    title: 'MINI Cooper S',
    variant: 'F56 · JCW Paket · Panorama · Adaptive',
    year: 2017,
    firstReg: '06/2017',
    price: 18800,
    priceDisplay: '18.800 €',
    km: 56000,
    status: 'prodano',
    fuel: 'Benzin',
    transmission: 'Automatik (7-stupanjski)',
    power: '141 kW / 192 KS',
    displacement: '1.998 ccm',
    color: 'Pepper White',
    bodyType: 'Hatchback',
    doors: 3,
    seats: 4,
    drive: 'FWD',
    vatIncluded: false,
    warranty: undefined,
    description: 'MINI Cooper S F56 s John Cooper Works aerodinamičkim paketom, panoramskim krovom i adaptivnim farovima.',
    equipment: ['JCW aerodinamički paket', 'Panoramski krov', 'Adaptivni farovi', 'JCW sport ovjes', 'Navigacija', 'Grijana sjedala', '17" JCW felge'],
    images: [
      { url: null, alt: 'Prednji lijevo' },
      { url: null, alt: 'Bočni lijevo' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
    ],
  },
  {
    id: 12,
    slug: 'vw-golf-8r-4motion',
    brand: 'VW',
    model: 'Golf 8R',
    title: 'VW Golf 8R',
    variant: '4Motion · 2.0 TSI · 320 KS',
    year: 2021,
    firstReg: '07/2021',
    price: 39800,
    priceDisplay: '39.800 €',
    km: 35000,
    status: 'prodano',
    fuel: 'Benzin',
    transmission: 'DSG (7-stupanjski)',
    power: '235 kW / 320 KS',
    displacement: '1.984 ccm',
    color: 'Lapiz Blue Metallic',
    bodyType: 'Hatchback',
    doors: 5,
    seats: 5,
    drive: 'AWD (4Motion)',
    vatIncluded: false,
    warranty: undefined,
    description: 'VW Golf 8R s 320 KS i 4Motion pogonom na sve kotače. Najbrži serijski Golf — Track modus, akrapovič ispuh dostupan po dogovoru.',
    equipment: ['R Performance sport ovjes', 'Digital Cockpit Pro', 'Akustično laminirano vjetrobransko staklo', 'Dynaudio Excite audio', 'IQ.Light LED Matrix farovi', 'Grijana sjedala', '19" Estoril felge', 'Driveline Manager'],
    images: [
      { url: null, alt: 'Prednji lijevo' },
      { url: null, alt: 'Bočni lijevo' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
    ],
  },
  {
    id: 13,
    slug: 'bmw-m140i-b58',
    brand: 'BMW',
    model: 'M140i',
    title: 'BMW M140i',
    variant: 'B58 · H&K · Adaptivni ovjes · LSD',
    year: 2018,
    firstReg: '03/2018',
    price: 32900,
    priceDisplay: '32.900 €',
    km: 86000,
    status: 'prodano',
    fuel: 'Benzin',
    transmission: 'Automatik (8-stupanjski)',
    power: '250 kW / 340 KS',
    displacement: '2.979 ccm',
    color: 'Melbourne Red Metallic',
    bodyType: 'Hatchback',
    doors: 5,
    seats: 5,
    drive: 'RWD',
    vatIncluded: false,
    warranty: undefined,
    description: 'BMW M140i s B58 motorom, LSD diferencijalnom, adaptivnim ovjesom i Harman/Kardon audio sustavom. Jedan od posljednjih pravih pogona na stražnje kotače u kompaktnoj klasi.',
    equipment: ['M Performance LSD (Quaife ATB)', 'Adaptivni M ovjes', 'Harman/Kardon audio', 'Kožna sport sjedala', '19" M felge', 'Sportski ispuh', 'Adaptivni tempomat', 'Head-Up Display'],
    images: [
      { url: null, alt: 'Prednji lijevo' },
      { url: null, alt: 'Bočni lijevo' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
    ],
  },
  {
    id: 14,
    slug: 'vw-id3-1st-edition',
    brand: 'VW',
    model: 'ID.3 1st Edition',
    title: 'VW ID.3',
    variant: '58 kWh · 1st Edition',
    year: 2021,
    firstReg: '04/2021',
    price: 31750,
    priceDisplay: '31.750 €',
    km: 77000,
    status: 'prodano',
    fuel: 'Električni',
    transmission: 'Automatik (1-stupanjski)',
    power: '150 kW / 204 KS',
    displacement: '58 kWh baterija',
    color: 'Manganese Grey Metallic',
    bodyType: 'Hatchback',
    doors: 5,
    seats: 5,
    drive: 'RWD',
    vatIncluded: false,
    warranty: undefined,
    description: 'VW ID.3 1st Edition s baterijom od 58 kWh i dometom do 420 km (WLTP). Najsuvremeniji kabinet s AR Head-Up Displayom i Harman/Kardon audio sustavom.',
    equipment: ['58 kWh baterija · 420 km WLTP', 'DC brzo punjenje (100 kW)', 'AR Head-Up Display', 'Harman/Kardon audio', 'Panoramski krov', 'Grijana sjedala i upravljač', 'Kamera 360°', 'Travel Assist'],
    images: [
      { url: null, alt: 'Prednji lijevo' },
      { url: null, alt: 'Bočni lijevo' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
    ],
  },
  {
    id: 15,
    slug: 'vw-t-cross-15-tsi-dsg',
    brand: 'VW',
    model: 'T-Cross 1.5 TSI DSG',
    title: 'VW T-Cross 1.5 TSI',
    variant: 'Style · 1.5 TSI DSG',
    year: 2022,
    firstReg: '05/2022',
    price: 22000,
    priceDisplay: 'Na upit',
    km: 38000,
    status: 'prodano',
    fuel: 'Benzin',
    transmission: 'DSG (7-stupanjski)',
    power: '110 kW / 150 KS',
    displacement: '1.498 ccm',
    color: 'Kings Red Metallic',
    bodyType: 'SUV',
    doors: 5,
    seats: 5,
    drive: 'FWD',
    vatIncluded: false,
    warranty: 'Do 05/2024',
    description: 'VW T-Cross 1.5 TSI u Style opremi s DSG mjenjačem. Odlično gradsko SUV vozilo s modernom opremom.',
    equipment: ['LED farovi', 'Navigacija', 'Digitalni kokpit', 'Automatska klima 2-zonska', 'Grijana prednja sjedala', 'Apple CarPlay / Android Auto', '17" aluminijske felge', 'ParkPilot'],
    images: [
      { url: null, alt: 'Prednji lijevo' },
      { url: null, alt: 'Bočni lijevo' },
      { url: null, alt: 'Stražnji' },
      { url: null, alt: 'Interijer' },
    ],
  },
]

export function getVehicleBySlug(slug: string): Vehicle | undefined {
  return ALL_VEHICLES.find((v) => v.slug === slug)
}
